openapi: 3.1.0
info:
  title: Сервис кеширования товаров
  description: Сервис, отвечающий за кеширование отдельных товаров и списков товаров (главной страницы)
  version: 1.0.0
servers:
  - url: http://localhost:8081
paths:
  /cache/item/{itemId}:
    post:
      summary: Добавить товар в кеш
      operationId: cacheItem
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID товара
      tags:
        - cache
      requestBody:
        required: true
        description: Кешируемый товар
        content:
          application/json; charset=utf-8:
            schema:
              $ref: '#/components/schemas/CachedItem'
      responses:
        '201':
          description: Статус сохранения
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/CacheSavedRs'
        '400':
          description: Ошибка сохранения товара в кеш
          content:
            application/json; charset=utf-8:
              schema:
                $ref: './payment-spec.yaml#/components/schemas/ErrorRs'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json; charset=utf-8:
              schema:
                $ref: './payment-spec.yaml#/components/schemas/ErrorRs'

    get:
      summary: Получить товар по ID
      operationId: getItemById
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID товара
      tags:
        - cache
      responses:
        '200':
          description: Товар найден
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/CachedItem'
        '204':
          description: Данные по товару в кеше не найдены
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json; charset=utf-8:
              schema:
                $ref: './payment-spec.yaml#/components/schemas/ErrorRs'

  /cache/main/items:
    post:
      summary: Сохранить список товаров главной страницы в кеш
      operationId: cacheMainItems
      parameters:
        - $ref: '#/components/parameters/SearchParam'
        - $ref: '#/components/parameters/SortParam'
        - $ref: '#/components/parameters/PageSizeParam'
        - $ref: '#/components/parameters/PageNumberParam'
      tags:
        - cache
      requestBody:
        required: true
        description: Список товаров, которые сохраняем в кеш
        content:
          application/json; charset=utf-8:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CachedItem'
      responses:
        '201':
          description: Статус сохранения
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/CacheSavedRs'
        '400':
          description: Ошибка сохранения списка товаров в кеш
          content:
            application/json; charset=utf-8:
              schema:
                $ref: './payment-spec.yaml#/components/schemas/ErrorRs'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json; charset=utf-8:
              schema:
                $ref: './payment-spec.yaml#/components/schemas/ErrorRs'

    get:
      summary: Получить список товаров из кеша по параметрам запроса
      operationId: getMainItemsByParams
      parameters:
        - $ref: '#/components/parameters/SearchParam'
        - $ref: '#/components/parameters/SortParam'
        - $ref: '#/components/parameters/PageSizeParam'
        - $ref: '#/components/parameters/PageNumberParam'
      tags:
        - cache
      responses:
        '200':
          description: Список товаров
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CachedItem'
        '204':
          description: Данные по товару в кеше не найдены
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json; charset=utf-8:
              schema:
                $ref: './payment-spec.yaml#/components/schemas/ErrorRs'

components:
  schemas:
    CachedItem:
      type: object
      required:
        - id
        - title
        - description
        - image
        - price
      properties:
        id:
          description: ID товара
          type: integer
          format: int64
          example: 1
        title:
          description: Название товара
          type: string
          example: Майка
        description:
          description: Описание товара
          type: string
          example: Чёрная
        image:
          description: Ресурс картинки
          type: string
          example: image1.png
        price:
          description: Цена товара
          type: integer
          format: int64
          example: 5000
    CacheSavedRs:
      type: object
      required:
        - saved
      properties:
        saved:
          description: Статус сохранения объекта в кеш
          type: boolean
          example: true
    SortEnum:
      type: string
      description: |
        Возможные варианты сортировки:
        * `NONE` — без сортировки
        * `ALPHA` — по алфавиту
        * `PRICE_ASC` — по возрастанию цены
        * `PRICE_DESC` — по убыванию цены
      enum:
        - NONE
        - ALPHA
        - PRICE_ASC
        - PRICE_DESC
      default: "NONE"
      example: "NONE"
  parameters:
    SearchParam:
      name: search
      in: query
      description: Строка поиска товаров
      required: false
      schema:
        type: string
        maxLength: 20
        default: ""
        example: Майка
    SortParam:
      name: sort
      in: query
      description: Параметр сортировки
      required: false
      schema:
        $ref: '#/components/schemas/SortEnum'
    PageSizeParam:
      name: pageSize
      in: query
      description: Количество товаров на странице
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
    PageNumberParam:
      name: pageNumber
      in: query
      description: Номер страницы (начиная с 0)
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
